title: Heath Reinhard's Technical Writing Portfolio
logo: /assets/img/logo.png
description: Technical Writer, Documentation Engineer, Man of Mystery
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
