title: Heath Reinhard
logo: /assets/img/logo.png
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..3
