#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site \
  --check-html \
  --check-sri \
  --assume-extension \
  --http-status-ignore 999,403 \
  --url-ignore "https://www.linkedin.com/in/heath-reinhard/,https://www.slant.co/versus/4557/12763/~irc_vs_mattermost" \
  --url-swap "^/portfolio/:/,^https\\://agentheath.github.io/portfolio/:/"
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
